# Generated by Django 4.2 on 2023-04-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
