# Generated by Django 4.2 on 2023-04-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_category_portfolio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='gmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
